#!/usr/bin/env bash

echo "Checking operating system..."
if [ $(uname -r | sed -n 's/.*\( *Microsoft *\).*/\1/ip') ]; then
    echo "Linux on WSL2 detected"

    echo "Check sudoers config..."
    CURRENT_USER=$USER
    if sudo ls /etc/sudoers.d/${CURRENT_USER} 2>/dev/null; then
        echo "Sudoers config already present for this user"
    else
        echo "Sudoers config not found, creating one... (using sudo)"
        sudo echo "${CURRENT_USER} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${CURRENT_USER} > /dev/null
    fi

    echo "Setup Git Credentials Manager"
    git config --global credential.helper "/mnt/c/Program\ Files/Git/mingw64/bin/git-credential-manager.exe"
    git config --global credential.useHttpPath true
    git config --global core.editor "vim"
    git config --global push.default current
    git config --global --add --bool push.autoSetupRemote true

    sudo apt update > /dev/null
    echo "Install zsh"
    sudo apt install zsh
    chsh -s /bin/zsh

    echo "Installing tmux"

    sudo apt install tmux

    echo "Installing starship"
    curl -sS https://starship.rs/install.sh | sh

    echo "Installing keychain"
    sudo apt install keychain

    echo "Installing kubectl"
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    chmod +x ./kubectl
    mkdir ~/bin
    mv ./kubectl ~/bin

    echo "Installing eza"
    sudo apt install eza

    echo "Installing az cli..."
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    echo "Installing miniconda..."
    mkdir -p ~/bin/miniconda
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/bin/miniconda/miniconda.sh
    bash ~/bin/miniconda/miniconda.sh -b -u -p ~/bin/miniconda
    rm -rf ~/bin/miniconda/miniconda.sh
    conda config --set changeps1 False
fi

echo "Creating symlinks..."
mkdir ~/.config
mkdir ~/.config/kitty
if [ -d ~/.zsh ] || [ -f ~/.zshrc ] || [ -f ~/.zshenv ]; then
    read -r -p "Another installation detected. Reinstall? [y|N] " response
    if [[ $response =~ (yes|y|Y) ]]; then
        ln -sivF ~/.dotfiles/.zsh ~
        ln -siv ~/.dotfiles/.zshenv ~/.zshenv
        ln -siv ~/.dotfiles/.zshrc ~/.zshrc
        ln -siv ~/.dotfiles/.tmux.conf ~/.tmux.conf
        ln -siv ~/.dotfiles/.config/kitty/kitty.conf ~/.config/kitty/kitty.conf
        ln -siv ~/.dotfiles/.config/starship.toml ~/.config/starship.toml
    else
        echo "Abording..."
    fi
else
    ln -sivF ~/.dotfiles/.zsh ~
    ln -siv ~/.dotfiles/.zshenv ~/.zshenv
    ln -siv ~/.dotfiles/.zshrc ~/.zshrc
    ln -siv ~/.dotfiles/.tmux.conf ~/.tmux.conf
    ln -siv ~/.dotfiles/.config/kitty/kitty.conf ~/.config/kitty/kitty.conf
    ln -siv ~/.dotfiles/.config/starship.toml ~/.config/starship.toml
fi
