#!/usr/bin/env bash

echo "Checking operating system..."
if [ $(uname -r | sed -n 's/.*\( *Microsoft *\).*/\1/ip') ]; then
    echo "Linux on WSL2 detected"

    echo "Check sudoers config..."
    CURRENT_USER=$USER
    if sudo ls /etc/sudoers.d/${CURRENT_USER} 2>/dev/null; then
        echo "Sudoers config already present for this user"
    else
        echo "Sudoers config not found, creating one... (using sudo)"
        sudo echo "${CURRENT_USER} ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${CURRENT_USER} > /dev/null
    fi
fi

echo "Creating symlinks..."
if [ -d ~/.zsh ] || [ -f ~/.zshrc ] || [ -f ~/.zshenv ]; then
    read -r -p "Another installation detected. Reinstall? [y|N] " response
    if [[ $response =~ (yes|y|Y) ]]; then
        ln -sivF ~/.dotfiles/.zsh ~
        ln -siv ~/.dotfiles/.zshenv ~/.zshenv
        ln -siv ~/.dotfiles/.zshrc ~/.zshrc
        ln -siv ~/.dotfiles/.tmux.conf ~/.tmux.conf
        ln -siv ~/.dotfiles/.config/kitty/kitty.conf ~/.config/kitty/kitty.conf
        ln -siv ~/.dotfiles/.config/starship.toml ~/.config/starship.toml
    else
        echo "Abording..."
    fi
else
    ln -sivF ~/.dotfiles/.zsh ~
    ln -siv ~/.dotfiles/.zshenv ~/.zshenv
    ln -siv ~/.dotfiles/.zshrc ~/.zshrc
    ln -siv ~/.dotfiles/.tmux.conf ~/.tmux.conf
    ln -siv ~/.dotfiles/.config/kitty/kitty.conf ~/.config/kitty/kitty.conf
    ln -siv ~/.dotfiles/.config/starship.toml ~/.config/starship.toml
fi
