format = "${custom.time}$all"
add_newline = false

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = "☁ "

[custom.time]
style = "yellow"
when = "true"
command = "echo \"$(date +%T)|$(date -u +%T) \""
format = '[\[$output\]]($style) '
